# syntax = docker/dockerfile:1

# Make sure RUBY_VERSION matches the Ruby version in .ruby-version
ARG RUBY_VERSION=3.4.7
FROM registry.docker.com/library/ruby:$RUBY_VERSION-slim AS base

# Rails app lives here
WORKDIR /rails

# Set development environment
ENV RAILS_ENV="development" \
    BUNDLE_PATH="/usr/local/bundle"

# Install packages needed for development
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y curl libsqlite3-0 libvips build-essential pkg-config git ffmpeg groff libreoffice-writer libreoffice-impress libreoffice-calc mupdf-tools libyaml-dev libssl-dev sqlite3 && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

# Install gum for bin/setup
RUN curl -fsSL https://github.com/charmbracelet/gum/releases/download/v0.17.0/gum_0.17.0_amd64.deb -o /tmp/gum.deb && \
    dpkg -i /tmp/gum.deb && \
    rm /tmp/gum.deb

# Install mise (runtime version manager)
RUN curl https://mise.run | sh && \
    ln -s /root/.local/bin/mise /usr/local/bin/mise

# Install application gems
COPY Gemfile Gemfile.lock .ruby-version ./
COPY lib/fizzy.rb ./lib/fizzy.rb
RUN --mount=type=cache,id=fizzy-devbundle-${RUBY_VERSION},sharing=locked,target=/devbundle \
    gem install bundler foreman && \
    BUNDLE_PATH=/devbundle bundle install && \
    cp -a /devbundle/. "$BUNDLE_PATH"/ && \
    bundle clean --force

# Final stage
FROM base

# Entrypoint prepares the database
ENTRYPOINT ["/rails/bin/docker-entrypoint"]

# Start the server by default
EXPOSE 3000
EXPOSE 3006
EXPOSE 5001
CMD ["./bin/thrust", "./bin/rails", "server"]
